### ISSUE TITLE
Build enhancement: Untracked dependency-reduced-pom.xml

### ISSUE THREAD

**Issue by pschoffer** [MutabilityDetector/MutabilityDetector#105]
When building the project using:
`mvn clean install`

New untracked by git file is generated: dependency-reduced-pom.xm

As I googled this is done by **maven-shade-plugin**.

There are 3 solution as far as I could think of:

1. Change the config of the plugin to not generate this file:
`<createDependencyReducedPom>false</createDependencyReducedPom>`

2. Add the file to git

3. Add the file to .gitignore

The solutions are in order how I would prefer to solve the issue (meaning I would vote for changing the plugin config). Of course I am more than happy do it myself, but I wanted to get your opinion on the issue before the PR.

**Comment by Grundlefleck** [comment]
I understand what generates this file, and what it contains, but I'm still unclear (after a short skim over the docs) whether it's actually required or not. The only time it is useful is when building a JAR that's going to be put on Maven Central, and since I'm the only person who has authority to do that, it's pointless for everyone else. However, I don't know if changing the config (option `1`) affects that release process or not.

If you make a PR for `3`, I'll merge it, then, the next time I'm releasing I'll look in more detail on whether `1` is a better fix.

Thanks for taking an interest!

**Comment by pschoffer** [comment]
Thanks for the commend. 3) was merged.

**Comment by sband** [comment]
Should this be closed ?

**Comment by pschoffer** [comment]
I think yes,

**Comment by Grundlefleck** [comment]
I concur.
