### ISSUE TITLE
Configurations.JDK_CONFIGURATION is ignored: String is actually NOT_IMMUTABLE

### ISSUE THREAD

**Issue by hexmind** [MutabilityDetector/MutabilityDetector#160]
```
MutabilityAsserter.configured(Configurations.JDK_CONFIGURATION)
    .assertImmutable(String.class);
```
Despite of `hardcoding analysis results` I get below error.

MutabilityDetector 0.10.3
openjdk 13.0.1
```
Expected: java.lang.String to be IMMUTABLE
     but: java.lang.String is actually NOT_IMMUTABLE
    Reasons:
        Field is not final, if shared across threads the Java Memory Model will not guarantee it is initialised before it is read. [Field: hash at java.lang.String(String.java:1)]
        Field [hash] can be reassigned within method [hashCode] [Field: hash at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field can have a mutable type (an array) assigned to it. [Field: value at java.lang.String(String.java:1)]
        Field is an array. [Field: value at java.lang.String(String.java:1)]
```

**Comment by Grundlefleck** [comment]
Hi @hexmind, thanks for getting in touch,

The behaviour you're seeing is actually by design, and described in the [documentation](https://javadoc.io/static/org.mutabilitydetector/MutabilityDetector/0.10.3/org/mutabilitydetector/unittesting/MutabilityAssert.html#TestHardcodedDirectly). 

Hardcoding results is designed for preventing false positives when _using_ an immutable class, e.g. as a field, and Mutability Detector gets it wrong. If you had a class `Foo` with a `private final String myField`, the hardcoded result will prevent Mutability Detector from thinking `Foo` is mutable because `myField` is mutable.

I decided to keep the "real" analysis for assertions on classes which are also hardcoded. Consider this case, you have your own class `Point`, and you decide to store x and y coordinates in a `private final int[]` array instead of two separate fields (as some kind of optimisation or something, bear with me). You are 100% sure that `Point` is immutable as the array cannot be modified, but Mutability Detector panics when it sees the array field and thinks it's mutable. So now every class that has a `Point` field is now also mutable. You know that's a mistake in Mutability Detector's analysis, so you hardcode `Point` as definitely immutable, and all your classes are now immutable, great! Except, what happens when some other developer comes along and accidentally makes your `int[]` field in `Point` public. No tests will fail, even though a class which should be immutable has been made mutable. To protect against that, you need to have the "real" analysis run against `Point`, and only suppress the false positives as tightly as possible, for some property you have manually reviewed. That test case should be written with something like `assertImmutable(Point.class)`, and it should ignore any hardcoded setting you have for `Point`.

Does that make sense?

**Comment by Grundlefleck** [comment]
Btw, if you want to override this behaviour, so that direct assertions use the hardcoded results, you can: https://javadoc.io/static/org.mutabilitydetector/MutabilityDetector/0.10.3/org/mutabilitydetector/ConfigurationBuilder.html#setHowToUseHardcodedResults-org.mutabilitydetector.config.HardcodedResultsUsage-

**Comment by hexmind** [comment]
Great, thank you for a detailed answer.
I thought I read a documentation but I miss `Testing Hardcoded Classes Directly` part. Now I understand that by default even hardcoded results are valid only in indirect way.

My test was changed to this one:
```
        JdkConfiguration configuration = new JdkConfiguration() {
            @Override
            public void configure() {
                super.configure();
                setHowToUseHardcodedResults(HardcodedResultsUsage.DIRECTLY_IN_ASSERTION);
            }
        };
        MutabilityAsserter.configured(configuration)
                .assertImmutable(String.class);
```

In case of immutable string wrapper additional configuration isn't needed.

**Comment by Grundlefleck** [comment]
@hexmind no problem, thanks for reporting. It also gives me a feel for where documentation / configuration is not obvious, which is helpful.

Out of curiosity, why are you testing immutability of `String.class`? Was it just to represent your issue more succinctly, or is that providing value in another way?

**Comment by hexmind** [comment]
I am just experimenting with immutability topic and related tools.

**Comment by Grundlefleck** [comment]
Cool, thanks.
