### ISSUE TITLE
IllegalArgumentException when using Java 16 and higher

### ISSUE THREAD

**Issue by l0s** [MutabilityDetector/MutabilityDetector#181]
The library currently cannot be used with Java 16.

When running the `ClientOfMutabilityDetector` tests with Java 16 (library built locally with 1.8), it produces the following results:

    Tests run: 172, Failures: 0, Errors: 26, Skipped: 1

_One_ of the failures includes this message:

    Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 60

This is the build environment I used to reproduce the issue:

    ; mvn --version
    Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
    Maven home: /usr/local/Cellar/maven/3.8.1/libexec
    Java version: 16.0.1, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-16.jdk/Contents/Home
    Default locale: en_GB, platform encoding: UTF-8
    OS name: "mac os x", version: "11.3", arch: "x86_64", family: "mac"

In addition, when building `MutabilityDetector` with Java 16, it produces the following test results:

    Tests run: 371, Failures: 0, Errors: 77, Skipped: 5

Again, one of the test failures includes the message:

    Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 60

**Comment by l0s** [comment]
This fails with Java 17 as well.

When running the `ClientOfMutabilityDetector` tests with Java 17 (library built locally with 11), it produces the following results:

    Tests run: 172, Failures: 0, Errors: 26, Skipped: 1

_One_ of the failures includes this message:

    Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
    	at org.mutabilitydetector.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)

This is the build environment I used to reproduce the issue:

    mvn --version
    Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
    Maven home: /usr/local/Cellar/maven/3.8.2/libexec
    Java version: 17, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
    Default locale: en_GB, platform encoding: UTF-8
    OS name: "mac os x", version: "11.5", arch: "x86_64", family: "mac"

In addition, when building `MutabilityDetector` with Java 17, it produces the following test results:

    Tests run: 371, Failures: 0, Errors: 77, Skipped: 5

Again, _one_ of the test failures includes the message:

    Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
    	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)

Unfortunately, I am not able to work around this issue by using a new asm version in downstream projects.

**Comment by Grundlefleck** [comment]
Apologies, I missed the notification of this. I aim to cut a new release soon (most likely using your PR).

**Comment by mcusack-nbcuni** [comment]
Why is this closed before the fix? We can't use this library right now with Java 16+.

**Comment by MikeJCusack** [comment]
Why is this closed before the fix? We can't use this library right now for Java 16+.

**Comment by MikeJCusack** [comment]
Also confused because @l0s mentioned here that his PR isn't resolving it for Java 17 (current LTS).

**Comment by Grundlefleck** [comment]
@MikeJCusack it was GitHub being "helpful". Because the PR used a keyword that implied merging would fix this issue, it got closed automatically:

![image](https://user-images.githubusercontent.com/461739/151260993-22b31e0c-2e3f-4df0-b254-f63ac7d4e2fe.png)
(note the "Resolves #xxx" which is described in [GitHub docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))


I believe #182 will fix this issue, as demonstrated in [this workflow run](https://github.com/MutabilityDetector/MutabilityDetector/runs/4958070723?check_suite_focus=true). What am I missing?

Reopening, and will close when there is a publicly available (Maven Central) artifact that works with up to Java 17.

Btw, there's a small discussion on the "meta-issue" of keeping up with Java releases without requiring a new release [here](https://github.com/MutabilityDetector/MutabilityDetector/issues/116#issuecomment-452904469). I don't know if I'll ever get to that myself, but I definitely would take the time to help a would-be contributor solve the problem.

**Comment by Grundlefleck** [comment]
@l0s @MikeJCusack 

0.10.6 has landed in Maven Central, with support up to Java 17. Please take it for a spin and confirm here that it solves your issue.

**Comment by l0s** [comment]
I can confirm this solves the issue. Thanks @Grundlefleck!
