### ISSUE TITLE
Add support for immutable collections of Google Guava

### ISSUE THREAD

**Issue by heri333** [MutabilityDetector/MutabilityDetector#39]
[Google Guava](https://code.google.com/p/guava-libraries/) provides several immutable utility classes, for example [ImmutableList](http://docs.guava-libraries.googlecode.com/git-history/release/javadoc/com/google/common/collect/ImmutableList.html).

If there is an assignment to a final field in a constructor like 

    this.foo = ImmutableList.of();

it is reported as

    org.mutabilitydetector.unittesting.MutabilityAssertionError: 
      Expected: ... to be IMMUTABLE
           but: ... is actually NOT_IMMUTABLE
          Reasons:
              Field can have an abstract type (com.google.common.collect.ImmutableList) assigned to it. [Field: foo, Class: ...]
          Allowed reasons:
              None.

**Comment by sbilinski** [comment]
Any news regarding this issue? I could really use Guava collection support, but I'm not sure if I should start implementing it on my own.

**Comment by Grundlefleck** [comment]
Hi @sbilinski, I've been keeping this issue around as something a new contributor could work on, but since there's interest in it, I'll bump the priority.

Are you more interested in contributing code to the project or in having it Just Work? I hope that doesn't sound "snippy", it's a genuine question, if you have a particular interest in contributing it, I'm more than happy to help towards that, otherwise, I'll pick it up myself.

Thanks!

**Comment by Grundlefleck** [comment]
Just released 0.9.3 with support for immutable collection types of Guava.

**Comment by Stephan202** [comment]
@Grundlefleck, this is pretty cool. However, for some reason it seems that `ImmutableSortedMap` is still deemed mutable. The first two tests in the following class _pass_, but the third _fails_:

	public final class ImmutabilityTest {
		// Passes
		@Test
		public void testWithImmutableMapField() {
			final class ImmutableMapWrapper {
				private final ImmutableMap<String, String> map = ImmutableMap.of();
			}
	
			MutabilityAssert.assertImmutable(ImmutableMapWrapper.class);
		}
	
		// Passes
		@Test
		public void testWithImmutableSortedMultisetField() {
			final class ImmutableSortedMultisetWrapper {
				private final ImmutableSortedMultiset<String> map = ImmutableSortedMultiset.of();
			}
	
			MutabilityAssert.assertImmutable(ImmutableSortedMultisetWrapper.class);
		}
	
		// Fails
		@Test
		public void testWithImmutableSortedMapField() {
			final class ImmutableSortedMapWrapper {
				private final ImmutableSortedMap<String, String> map = ImmutableSortedMap.of();
			}
	
			MutabilityAssert.assertImmutable(ImmutableSortedMapWrapper.class);
		}
	}

The reported error is:

	org.mutabilitydetector.unittesting.MutabilityAssertionError: 
		Expected: com.example.ImmutabilityTest$1ImmutableSortedMapWrapper to be IMMUTABLE
		     but: com.example.ImmutabilityTest$1ImmutableSortedMapWrapper is actually NOT_IMMUTABLE
		    Reasons:
		        Field can have an abstract type (org.mutabilitydetector.internal.com.google.common.collect.ImmutableSortedMap) assigned to it. [Field: map, Class: com.example.ImmutabilityTest$1ImmutableSortedMapWrapper]
		    Allowed reasons:
		        None.

Interestingly, `org.mutabilitydetector.config.GuavaConfiguration` does explicitly list `ImmutableSortedMap` (just like the other two).

NB: If you prefer I can file a separate issue for this.

**Comment by Grundlefleck** [comment]
Hi @Stephan202,

This is a problem with your imports -- but it's introduced because of how I package the Jar, so apologies :)

The imported ImmutableSortedMap comes from the repackaged version of Guava that Mutability Detector uses. The clue is in this message:
`Field can have an abstract type (org.mutabilitydetector.internal.com.google.common.collect.ImmutableSortedMap) assigned to it.`

Note the `org.mutabilitydetector.internal` prefix on the package. If you change the imports to point directly to `com.google.common.collect.ImmutableSortedMap` it should be fine.

I'm assuming that the reason the repackaged class gets picked up is because of the automatic import feature of whichever IDE you're using. I believe most IDEs allow this feature to be configured, and I have observed the convention of excluding an import matching `*.internal.*`, which is why I picked that package name.

Lemme know if that's not the issue.

**Comment by Stephan202** [comment]
Hi @Grundlefleck, very good catch. I should have seen that... :/ Fixing the imports makes the test pass.

The reason I created the test cases in the first, place, however, is that I did have an issue with `ImmutableSortedMap` in code that was written before Mutability Detector was even on the classpath. (I.e., no incorrect `import` statements.) This is a an example that's closer to the real code (note the nesting):

	// Fails
	@Test
	public void testWithImmutableSortedMapField2() {
		final class ImmutableSortedMapWrapper {
			private final ImmutableSortedMap<String, ImmutableSortedMultiset<String>> map = ImmutableSortedMap.of();
		}

		MutabilityAssert.assertImmutable(ImmutableSortedMapWrapper.class);
	}

This test fails with the following error (observe how the error message makes it appear that `ImmutableSortedMap` takes three type parameters):

	org.mutabilitydetector.unittesting.MutabilityAssertionError: 
		Expected: com.example.ImmutabilityTest$2ImmutableSortedMapWrapper to be IMMUTABLE
		     but: com.example.ImmutabilityTest$2ImmutableSortedMapWrapper is actually NOT_IMMUTABLE
		    Reasons:
		        Field can have collection with mutable element type (com.google.common.collect.ImmutableSortedMap<java.lang.String, com.google.common.collect.ImmutableSortedMultiset, java.lang.String>) assigned to it. [Field: map, Class: com.example.ImmutabilityTest$2ImmutableSortedMapWrapper]
		    Allowed reasons:
		        None.

Thanks for having a look :)

**Comment by Grundlefleck** [comment]
Ah yes, nested generics is a known problem. I'll open another issue for that.
