### ISSUE TITLE
Update the wiki/homepage/readme/etc with information on new gitter room

### ISSUE THREAD

**Issue by Grundlefleck** [MutabilityDetector/MutabilityDetector#72]
The project recently got it's own gitter room: https://gitter.im/MutabilityDetector/main

It would be cool if the various places that a newcomer sees included links to the gitter room. These include:

- the homepage at mutabilitydetector.org (hosted by GitHub Pages)
- README.md
- CONTRIBUTING.md
- any pages on the wiki that provide contact information

**Comment by Grundlefleck** [comment]
A badge in the readme, such as the one from this automated pull request would be cool too:

https://github.com/MutabilityDetector/MutabilityDetector4FindBugs/pull/7

**Comment by jagan387** [comment]
This issue is fixed:
README.md, CONTRIBUTING.md and the wiki already have the gitter room badge. The homepage, though it does not have a direct link, has contact page, which in turn has the gitter badge. We need to mark this as fixed.

Although the home page http://mutabilitydetector.org/ has  a small glitch at the end, in the "Mutability Detector Blog" section which says, "Unable to retrieve spec for http://google-code-feed-gadget.googlecode.com/svn/trunk/gadget.xml. HTTP error 404". The script which you wrote is probably not working. Maybe you could open a new issue and fix this.

**Comment by Grundlefleck** [comment]
Thanks for pointing out. I will close this and open a new issue for the RSS feed widget.

(For this, and the other issues and pull requests you've been active on recently, I'm sorry it's taken so long to reply, I've been on holiday.)

**Comment by Grundlefleck** [comment]
Opened #88.
