### ISSUE TITLE
The fix for #90 is missing test coverage

### ISSUE THREAD

**Issue by Grundlefleck** [MutabilityDetector/MutabilityDetector#92]
Issue #90 has been fixed, but the fix was merged without test coverage. This issue is to provide test coverage to help prevent regressions of the problem that led to #90.

**Comment by Grundlefleck** [comment]
@mohamed-fadl interested in this?

**Comment by Grundlefleck** [comment]
I'm holding back information on how **I** would provide test coverage here, to give would-be contributors a chance to think about the problem. I'm happy to give advice when required. HINT: my expectation is that the code of `SessionResultsFormatter` would change to facilitate easier testability.

**Comment by mohamed-fadl** [comment]
will look at it :)

**Comment by civild** [comment]
There's several ways I can think of:
* Scan the output of a current test case, parse the number of seconds and assert that it is >=0
  * Not the best, especially since the number of seconds for most tests will be 0
* Add startTime as a parameter to appendSummaryOfResults and change it to package-local, then write a test just for that method
  * More direct, but changing the scope may not be desired
* Use Powermock to force the values returned by System.currentTimeMillis() and ManagementFactory.getRuntimeMXBean().getStartTime() so you can check for a specific answer in the output
  * Likely a lot of setup for not much gain
* Move the start and end time calls above into a utility class, which you can then mock in the test to return specific values, and check the output contains that value
  * I like this approach as you can re-use these elsewhere for start time of VM or current time if necessary

Interested to hear your thoughts - maybe I'm over-thinking it :grin:

**Comment by Grundlefleck** [comment]
I like the last option the best. When it comes to anything time or date based, I like to make sure that I can always test the effects of time passing within a unit test. That way I can check all the expected conditions in a way that's fast (no waiting for actual time to elapse, and no `Thread.sleep` that makes tests slow) and deterministic (doesn't matter when or how quickly it runs, it always has the same result).

I can think of two options for making the timing testable: pass in either a Guava `Stopwatch` with a custom `Ticker`, or a `java.time.Clock`, which can be mocked with Mockito. I think either approach would be good.

Happy to provide more info if needed.

**Comment by civild** [comment]
Great, I'll take a look and send a pull request with my solution.

**Comment by emmahastings** [comment]
Hi,

Is this issue still available, looks to me like it may have been fixed in https://github.com/MutabilityDetector/MutabilityDetector/pull/101.

Thanks,
Emma

**Comment by jlengrand** [comment]
Agreed @emmahastings

**Comment by Grundlefleck** [comment]
You are correct @emmahastings. Sloppiness on my part. Thank you :+1:
